
language: go

go:
  - 1.7
  - master
env:
  global:
    - GOOS="windows"
    - GOARCH="amd64"
    
script: 
  - GOOS=windows GOARCH=amd64 go build
  - GOOS=linux GOARCH=amd64 go build
  - ls -ltr
deploy:
  provider: releases
  api_key: "48f8a735aeb5ce5433ebcb2f941b045fd80ef566"
  file: 
    - "flardy.exe"
    - "flardy"
  skip_cleanup: true
  on:
    tags: true
