
language: go

go:
  - 1.7
  - master
env:
  global:
    - GOOS="windows"
    - GOARCH="amd64"
    
script: 
  - GOOS=windows GOARCH=amd64 go build
  - GOOS=linux GOARCH=amd64 go build
  - ls -ltr
deploy:
  provider: releases
  api_key: "0c42e48931c12327fabcd446b01f20baa1c2e18d"
  file: 
    - "flardy.exe"
    - "flardy"
  skip_cleanup: true
  on:
    tags: true
