
language: go

go:
  - 1.7
  - master
env:
  global:
    - GOOS="windows"
    - GOARCH="amd64"
    
script: 
  - GOOS=windows GOARCH=amd64 go build
  - GOOS=windows GOARCH=amd64 go build
  - ls -ltr
deploy:
  provider: releases
  api_key: "7b74c1c5c9e0a3881bb46d7e520f2dab307e90b7"
  file: 
    - "flardy.exe"
    - "flardy"
  skip_cleanup: true
  on:
    tags: true
